# Generated by Django 3.2.4 on 2021-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('areaOfFloor', models.IntegerField(null=True)),
                ('buildingConstrucionYear', models.IntegerField(null=True)),
                ('buildingFloorNumber', models.IntegerField(null=True)),
                ('buildingType', models.CharField(choices=[('Betonarme', 'Betonarme'), ('Yığma', 'Yığma'), ('Çelik', 'Çelik')], max_length=255, null=True)),
                ('buildingUsageClass', models.CharField(choices=[('BKS1', 'BKS1'), ('BKS2', 'BKS2'), ('BKS3', 'BKS3')], max_length=255, null=True)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('distanceToGroundBreak', models.IntegerField(null=True)),
                ('isFilledGround', models.CharField(max_length=1, null=True)),
                ('isLiquefactonOnGround', models.CharField(max_length=1, null=True)),
                ('isPossibleOxidationInEarthquakeWaves', models.CharField(max_length=1, null=True)),
                ('isSafe', models.CharField(max_length=1, null=True)),
                ('maxGroundAcceleration', models.IntegerField(null=True)),
                ('possibilityToAffectTheArea', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='vs30json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, null=True)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('vs30', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
