# Generated by Django 3.2.4 on 2021-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='distanceToGroundBreak',
        ),
        migrations.RemoveField(
            model_name='report',
            name='isFilledGround',
        ),
        migrations.RemoveField(
            model_name='report',
            name='isLiquefactonOnGround',
        ),
        migrations.RemoveField(
            model_name='report',
            name='isPossibleOxidationInEarthquakeWaves',
        ),
        migrations.RemoveField(
            model_name='report',
            name='isSafe',
        ),
        migrations.RemoveField(
            model_name='report',
            name='maxGroundAcceleration',
        ),
        migrations.RemoveField(
            model_name='report',
            name='possibilityToAffectTheArea',
        ),
        migrations.AddField(
            model_name='report',
            name='vs30',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
