# Generated by Django 3.2.4 on 2021-06-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210615_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vs30json',
        ),
    ]
